### ISSUE TITLE
Provide OCS-Store.AppImage on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [opendesktop/issues#14]
Please provide OCS-Store.AppImage on [GitHub Releases](https://github.com/opendesktop/ocsstore/releases).
Let me know if you are running into any issues, I am happy to help.

There is https://github.com/opendesktop/ocsstore/commits/develop/pkg/appimage/appimage.sh but it doesn't seem to be going anywhere at the moment. Is there a reason you are using electron-packager rather than [electron-builder](https://github.com/electron-userland/electron-builder), which has native AppImage support?

P.S.: Please enable GitHub Issues on https://github.com/opendesktop/ocsstore/, that would be easier for communicating, thanks.

**Comment by star-buck** [comment]
Now Enabled: https://github.com/opendesktop/ocsstore/issues
