### ISSUE TITLE
 Please enable GitHub and Google logins

### ISSUE THREAD

**Issue by probonopd** [opendesktop/issues#3]
(Continued from [here](https://forum.opendesktop.org/t/please-enable-github-and-google-logins/522))

Currently it is much harder than necessary to log in to forum.opendesktop.org because
* The login that works on, e.g., linux-appimages.org, is not recognized by forum.opendesktop.org
* It is not even possibly to use the same password on forum.opendesktop.org as on linux-appimages.org because apparently they have different rules for passwords
* Having to remember 1-2 new logins is just a pain and will prevent many users from even using these sites.
Please enable __GitHub logins__ and __Google logins__ for this forum. Discourse (the software that powers this forum) provides an easy way to do this. I know, because I am using this on http://discourse.appimage.org ;-)

<img src="https://forum.opendesktop.org/uploads/default/original/1X/cf0656f25961fbf155d73ea6fe25efe6b953cb80.png" width="440" height="289">

Go to __Admin -> Settings -> Login -> enable github logins__, and enter github client id and github client secret. Do the same for Google accounts. If you also check sso overrides bio, sso overrides email, sso overrides username, sso overrides name, sso overrides avatar, then all the user information is nicely in sync and users don't have to enter it yet again for yet another site...

__Of course it would be awesome if the same login methods would be available for the actual openDesktop sites as well, not just for this forum. One can dream :-)__

**Comment by star-buck** [comment]
We now allow Github, but dont care for google.
