### ISSUE TITLE
Icons are squeezed in "My Products" view

### ISSUE THREAD

**Issue by probonopd** [opendesktop/issues#6]
The icons are squeezed in the "My Products" view, resulting in an ugly look. Note they are not squeezed on the normal homepage view.

![screenshot at 2017-02-19 19 28 05](https://cloud.githubusercontent.com/assets/2480569/23105097/9fd604d6-f6d9-11e6-9941-80b585cf0e42.png)

**Comment by rvs75** [comment]
Done
