### ISSUE TITLE
Please allow OBS links

### ISSUE THREAD

**Issue by probonopd** [opendesktop/issues#9]
@adrianschroeter has implemented magic AppImage powers for http://openbuildservice.org/.

![OBS](http://openbuildservice.org/images/obs-logo.png)

Please allow AppImages hosted in OBS locations such as https://download.opensuse.org/repositories/home:/adrianSuSE:/AppImage/AppImage/ to be submitted to OD sites such as https://www.linux-appimages.org/, and ideally grab the latest versions automatically.

Perhaps OBS even provides a nice API that OD could leverage?

**Comment by adrianschroeter** [comment]
On Montag, 27. Februar 2017, 14:55:55 CET wrote probonopd:
> @adrianschroeter has implemented magic AppImage powers for http://openbuildservice.org/.
> 
> Please allow hosted AppImages such as https://download.opensuse.org/repositories/home:/adrianSuSE:/AppImage/AppImage/ to be submitted to OD sites such as https://www.linux-appimages.org/, and ideally grab the latest versions automatically.
> 
> Perhaps OBS even provides a nice API that OD could leverage?

We even used to have a general support of open-desktop, but I am not aware of the current state.

What kind of informations would you need?

Another important issue here is that really _EVERYBODY_ can build AppImages in OBS 
now. So you would need some kind of sorting, filtering or any other mechanics to
give your users some informations how much they can trust the builds.
Maybe we would just start with some single official project initially where 
people can submit their builds?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by probonopd** [comment]
> We even used to have a general support of open-desktop, but I am not aware of the current state. 

Yay! :+1: 

> What kind of informations would you need?

According to the [documentation](https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/#index36h4), looks like
- name - the name of the entry
- type - the type or category of the entry. call the categories method to get a list of all categories.
- downloadtyp1 - the type of the first download. possible values are: 0 - use the uploaded file, 1 - use the downloadlink1, 2 - use downloadpackagename and downloadrepository
- downloadname1 - the name of the 1. downloadlink
- downloadlink1 - the url of the downloadlink
- downloaddistributiontype1 - the type of the distribution for the download. call /v1/content/distributions for a list of possible options
- downloadpackagename1 - the name of the package in the repository
- downloadpackagerepository1 - the repository where the package is located
- description - a description text of the entry
- summary - a short summary of the entry
- licensetype - the license this content is under. get the possible values by calling /v1/content/licenses
- license - the license text
- feedbackurl - a link to the page where users can post feedback
- homepage - a link to the homepage of the entry
- homepagetype - the type of the link. get the possible values by calling /v1/content/homepages
- version - the version of this entry
- changelog - the changelog of this entry
- **osbsproject** - the opensuse build service project id
- **osbspackage** - the opensuse build service package id 

But I think we also need an icon (could be extracted from the package?) and optionally a screenshot, although I don't see them in the documentation linked above. Maybe @rvs75 or @star-buck can comment.

> Another important issue here is that really _EVERYBODY_ can build AppImages in OBS now. So you would need some kind of sorting, filtering or any other mechanics to give your users some informations how much they can trust the builds.

Very good point.

Does OBS have the concept of "maintained by upstream" repos/builds? I mean, I would trust an AppImage coming directly from the application's author/team, but not one from a random guy.

**Comment by star-buck** [comment]
We could allow external links to any files hosted under https://download.opensuse.org
As for the "general support of opendesktop", what exactly does that mean?

**Comment by probonopd** [comment]
Yes, allowing external links to files hosted on https://download.opensuse.org would be a great first step.

(The next step will involve thinking about how to inform the store that new AppImages are available there.)

**Comment by star-buck** [comment]
@probonopd : 
That should be possible now to add File-URLs that link to opensuse.

**Comment by probonopd** [comment]
Thank you.
